/*
 * AUTHOR : E DHRUV
 * DATE : 21/03/2020
 * TIME : 11:02:36
 */
package tambola;

import java.awt.Color;
import java.awt.Component;
import java.util.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class main extends javax.swing.JFrame {

    int visit[],P1_count,P2_count;
    Boolean isPlaying;
    basket b;
    JButton top_1[],top_2[],mid_1[],mid_2[],last_1[],last_2[];
    public main() {
        this.P1_count=0;
        this.P2_count=0;
        this.isPlaying = false;
        this.top_1 = new JButton[20];
        this.top_2 = new JButton[20];
        this.mid_1 = new JButton[20];
        this.mid_2 = new JButton[20];
        this.last_1 = new JButton[20];
        this.last_2 = new JButton[20];
        this.visit = new int[200];
        for(int i=1;i<=90;i++)
            visit[i] = 0;
        initComponents();
        init();
        addAction();
    }

    /**
     * Creates new form main
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String getSelectedRadioButton()
    {
        Enumeration<AbstractButton> allButtons = Player_Group.getElements();
        while(allButtons.hasMoreElements())
        {
            AbstractButton temp;
            temp = allButtons.nextElement();
            if(temp.isSelected())
                return temp.getText();
        }
        return "";
    }
    private boolean isNumeric(String s)
    {
        if(s == null)
            return false;
        try
        {
            int num = Integer.parseInt(s);
        }
        catch(NumberFormatException n)
        {
            return false;
        }
        return true;
    }
    private ActionListener createAction(JButton b1)
    {
        int label_num[] = new int[200];
        for(int i=1;i<90;i++) label_num[i]=0;
        ActionListener a1;
        a1 = (ActionEvent e) -> {
            if(b1.getText().equals("PICK"))
            {
                Random r = new Random();
                int num = 1+ r.nextInt(89);
                int cnt =1;
                while(label_num[num] != 0 && cnt < 90)
                {
                    cnt++;
                    num = 1+ r.nextInt(89);
                }
                if(cnt >= 90)
                {
                    getWinner();
                }
                else
                {
                    label_num[num]=1;
                    NUMBER.setText(String.valueOf(num));
                    b.markText(NUMBER.getText());
                }
            }
            else if("BASKET".equals(b1.getText()))
            {
                //TODO
                b.setVisible(true);
            }
            else if(b1.getText().equals("PLAY"))
            {
                
                Btn2.setText("PICK"); Btn1.setText("BASKET");
                top_level.setVisible(true); middle_row.setVisible(true);
                last_row.setVisible(true);  early_five.setVisible(true);
                four_corner.setVisible(true); player_1.setVisible(true);
                full_table.setVisible(true);
                player_2.setVisible(true); isPlaying = true;
                
            }
            else if(b1.getText().equals("EXIT"))
            {
                
                System.exit(0);
            }
            else if( isPlaying && isNumeric(b1.getText()))
            {
                if(NUMBER.getText().equals(b1.getText()) )
                {
                    b.markText(b1.getText());
                    b1.setBackground(Color.CYAN);
                    b1.setText("X");
                    //b1.disable();
                }
            }
        };
        return a1;
    }
    private void addAction()
    {
        Component[] comp = jPanel1.getComponents();
        for(Component c : comp)
        {
            if( c instanceof JButton )
            {
                JButton b1 = (JButton)c;
                    b1.addActionListener(createAction(b1));                
            }
        }
    }
    /*
         
    */
    private void init()
    {
        b = new basket();
        top_level.setVisible(false);
        middle_row.setVisible(false);
        last_row.setVisible(false);
        early_five.setVisible(false);
        four_corner.setVisible(false);
        full_table.setVisible(false);
        player_1.setVisible(false);
        player_2.setVisible(false);
        //TOP ROW OF FIRST PLAYER
        top_1[0]=top1_1; top_1[1] = top1_2; top_1[2] = top1_3;
        top_1[3]=top1_4; top_1[4] = top1_5; top_1[5] = top1_6;
        top_1[6]=top1_7; top_1[7] = top1_8; top_1[8] = top1_9;
        //MIDDLE ROW OF FIRST PLAYER
        mid_1[0]=mid1_1; mid_1[1] = mid1_2; mid_1[2] = mid1_3;
        mid_1[3]=mid1_4; mid_1[4] = mid1_5; mid_1[5] = mid1_6;
        mid_1[6]=mid1_7; mid_1[7] = mid1_8; mid_1[8] = mid1_9;
        //LAST ROW OF FIRST PLAYER
        last_1[0]=last1_1; last_1[1] = last1_2; last_1[2] = last1_3;
        last_1[3]=last1_4; last_1[4] = last1_5; last_1[5] = last1_6;
        last_1[6]=last1_7; last_1[7] = last1_8; last_1[8] = last1_9;
        
        
        //TOP ROW OF SECOND PLAYER
        top_2[0]=top2_1; top_2[1] = top2_2; top_2[2] = top2_3;
        top_2[3]=top2_4; top_2[4] = top2_5; top_2[5] = top2_6;
        top_2[6]=top2_7; top_2[7] = top2_8; top_2[8] = top2_9;
        //MIDDLE ROW OF SECOND PLAYER
        mid_2[0]=mid2_1; mid_2[1] = mid2_2; mid_2[2] = mid2_3;
        mid_2[3]=mid2_4; mid_2[4] = mid2_5; mid_2[5] = mid2_6;
        mid_2[6]=mid2_7; mid_2[7] = mid2_8; mid_2[8] = mid2_9;
        //LAST ROW OF FIRST PLAYER
        last_2[0]=last2_1; last_2[1] = last2_2; last_2[2] = last2_3;
        last_2[3]=last2_4; last_2[4] = last2_5; last_2[5] = last2_6;
        last_2[6]=last2_7; last_2[7] = last2_8; last_2[8] = last2_9;
        
        fillRow(top_1); fillRow(mid_1); fillRow(last_1);
        fillRow(top_2); fillRow(mid_2); fillRow(last_2);
        fillColumn(1);
        fillColumn(0);
    }
    private int getColumnDetails(int index,int flag)
    {
        int cnt = 3;
        if(flag == 1)
        {
            if(top_1[index].getText().equals(""))
                cnt-=1;
            if(mid_1[index].getText().equals(""))
                cnt-=1;
            if(last_1[index].getText().equals(""))
            cnt -=1;
        }
        else
        {
            if(top_2[index].getText().equals(""))
                cnt-=1;
            if(mid_2[index].getText().equals(""))
                cnt-=1;
            if(last_2[index].getText().equals(""))
            cnt -=1;
        }
        return cnt;
    }
    private String fillColumnHelper(JButton b1[],int flag)
    {
        for(int i=0;i<9;i++)
        {
            if(!b1[i].getText().equals("") && getColumnDetails(i,flag) >= 2)
            {
                String x = b1[i].getText();
                b1[i].setText("");
                return x;
            }
        }
        return "";
    }
    private void fillColumn(int flag)
    {
        
        for(int i=0;i<9;i++)
        {
            if( getColumnDetails(i,flag) == 0)
            {
                String num;
                Random r = new Random();
                int in =  r.nextInt(3);
                if(flag == 1)
                {
                    switch (in) 
                    {
                        case 0: num = fillColumnHelper(top_1,flag);
                                top_1[i].setText(num);
                            break; 
                        case 1: num = fillColumnHelper(mid_1,flag);
                                mid_1[i].setText(num);
                            break;
                        case 2: num = fillColumnHelper(last_1,flag);
                                last_1[i].setText(num);
                            break;
                    }
                }
                else
                {
                    switch (in) 
                    {
                        case 0: num = fillColumnHelper(top_2,flag);
                                top_2[i].setText(num);
                            break; 
                        case 1: num = fillColumnHelper(mid_2,flag);
                                mid_2[i].setText(num);
                            break;
                        case 2: num = fillColumnHelper(last_2,flag);
                                last_2[i].setText(num);
                            break;
                    }
                }
            }
        }
    }
    private void fillRow(JButton b1[])
    {
        int row[] = new int[20];
        for(int i=0;i<9;i++) row[i] = 0;
        Random r = new Random();
        for(int i=1;i<=5;i++)
        {
            int in = 1+r.nextInt(8);
            while(row[in] != 0)
            {
                in =  r.nextInt(9);
            }
            row[in]=1;
            int value = 1+r.nextInt(89);
            while(visit[value] != 0)
            {
                value = 1+r.nextInt(89);
            }
            visit[value]=1;
            b1[in].setText(String.valueOf(value));
        }
    }
    private void getWinner()
    {
        if(P1_count > P2_count)
                JOptionPane.showMessageDialog(this, "Congratualations! Player-1 won the game", "WINNER", JOptionPane.INFORMATION_MESSAGE);
        else if(P2_count > P1_count)
                JOptionPane.showMessageDialog(this, "Congratualations! Player-2 won the game", "WINNER", JOptionPane.INFORMATION_MESSAGE);
        else
            
                JOptionPane.showMessageDialog(this, "It's a Tie! Really close game", "WINNER", JOptionPane.INFORMATION_MESSAGE);

        int dialogOption = JOptionPane.showConfirmDialog(this, "Do you wish to play again?", "TAMBOOLA", JOptionPane.YES_NO_OPTION);
        if(dialogOption == JOptionPane.NO_OPTION)
        {
            JOptionPane.showConfirmDialog(this, "THANK YOU!", "TAMBOOLA", JOptionPane.OK_OPTION);
            System.exit(0);
        }
        else
            restart();
    }
    private void restart()
    {
         Btn1.setText("EXIT");
         Btn2.setText("PLAY");
         score_1.setText("");
         score_2.setText("");
         NUMBER.setText("");
         b = null;
         for(int i=0;i<9;i++)
         {
             if(top_1[i].getText().equals("X"))
             {
                 top_1[i].setText("");
                 top_1[i].setBackground(Color.WHITE);
             }
             if(mid_1[i].getText().equals("X"))
             {
                 mid_1[i].setText("");
                 mid_1[i].setBackground(Color.WHITE);
             }
             if(last_1[i].getText().equals("X"))
             {
                 last_1[i].setText("");
                 last_1[i].setBackground(Color.WHITE);
             }
             if(top_2[i].getText().equals("X"))
             {
                 top_2[i].setText("");
                 top_2[i].setBackground(Color.WHITE);
             }
             if(mid_2[i].getText().equals("X"))
             {
                 mid_2[i].setText("");
                 mid_2[i].setBackground(Color.WHITE);
             }
             if(last_2[i].getText().equals("X"))
             {
                 last_2[i].setText("");
                 last_2[i].setBackground(Color.WHITE);
             }
         }
         init();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Player_Group = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        NUMBER = new javax.swing.JLabel();
        top1_1 = new javax.swing.JButton();
        top1_3 = new javax.swing.JButton();
        top1_2 = new javax.swing.JButton();
        top1_6 = new javax.swing.JButton();
        top1_5 = new javax.swing.JButton();
        top1_4 = new javax.swing.JButton();
        top1_9 = new javax.swing.JButton();
        top1_8 = new javax.swing.JButton();
        top1_7 = new javax.swing.JButton();
        mid1_9 = new javax.swing.JButton();
        mid1_8 = new javax.swing.JButton();
        mid1_7 = new javax.swing.JButton();
        mid1_6 = new javax.swing.JButton();
        mid1_5 = new javax.swing.JButton();
        mid1_4 = new javax.swing.JButton();
        mid1_3 = new javax.swing.JButton();
        mid1_2 = new javax.swing.JButton();
        mid1_1 = new javax.swing.JButton();
        last1_9 = new javax.swing.JButton();
        last1_8 = new javax.swing.JButton();
        last1_7 = new javax.swing.JButton();
        last1_6 = new javax.swing.JButton();
        last1_5 = new javax.swing.JButton();
        last1_4 = new javax.swing.JButton();
        last1_3 = new javax.swing.JButton();
        last1_2 = new javax.swing.JButton();
        last1_1 = new javax.swing.JButton();
        top2_9 = new javax.swing.JButton();
        mid2_9 = new javax.swing.JButton();
        last2_9 = new javax.swing.JButton();
        last2_8 = new javax.swing.JButton();
        mid2_8 = new javax.swing.JButton();
        top2_8 = new javax.swing.JButton();
        top2_7 = new javax.swing.JButton();
        mid2_7 = new javax.swing.JButton();
        last2_7 = new javax.swing.JButton();
        last2_6 = new javax.swing.JButton();
        mid2_6 = new javax.swing.JButton();
        top2_6 = new javax.swing.JButton();
        top2_5 = new javax.swing.JButton();
        top2_4 = new javax.swing.JButton();
        top2_3 = new javax.swing.JButton();
        top2_2 = new javax.swing.JButton();
        top2_1 = new javax.swing.JButton();
        mid2_1 = new javax.swing.JButton();
        last2_1 = new javax.swing.JButton();
        last2_2 = new javax.swing.JButton();
        last2_3 = new javax.swing.JButton();
        mid2_2 = new javax.swing.JButton();
        last2_4 = new javax.swing.JButton();
        last2_5 = new javax.swing.JButton();
        mid2_5 = new javax.swing.JButton();
        mid2_4 = new javax.swing.JButton();
        mid2_3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        player_1 = new javax.swing.JRadioButton();
        player_2 = new javax.swing.JRadioButton();
        early_five = new javax.swing.JButton();
        top_level = new javax.swing.JButton();
        middle_row = new javax.swing.JButton();
        last_row = new javax.swing.JButton();
        four_corner = new javax.swing.JButton();
        full_table = new javax.swing.JButton();
        rules = new javax.swing.JButton();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        score_1 = new javax.swing.JLabel();
        score_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(80, 99, 139));

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBOOLA GAME");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 51));

        Btn1.setBackground(new java.awt.Color(51, 0, 51));
        Btn1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        Btn1.setForeground(new java.awt.Color(204, 204, 255));
        Btn1.setText("EXIT");
        Btn1.setBorder(null);
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setBackground(new java.awt.Color(51, 0, 51));
        Btn2.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        Btn2.setForeground(new java.awt.Color(204, 204, 255));
        Btn2.setText("PLAY");
        Btn2.setBorder(null);
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        NUMBER.setBackground(new java.awt.Color(255, 0, 51));
        NUMBER.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        NUMBER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUMBER.setToolTipText("");

        top1_1.setBackground(new java.awt.Color(255, 255, 255));
        top1_1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_3.setBackground(new java.awt.Color(255, 255, 255));
        top1_3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_2.setBackground(new java.awt.Color(255, 255, 255));
        top1_2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_6.setBackground(new java.awt.Color(255, 255, 255));
        top1_6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_5.setBackground(new java.awt.Color(255, 255, 255));
        top1_5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_4.setBackground(new java.awt.Color(255, 255, 255));
        top1_4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_9.setBackground(new java.awt.Color(255, 255, 255));
        top1_9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_8.setBackground(new java.awt.Color(255, 255, 255));
        top1_8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top1_7.setBackground(new java.awt.Color(255, 255, 255));
        top1_7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top1_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_9.setBackground(new java.awt.Color(255, 255, 255));
        mid1_9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_8.setBackground(new java.awt.Color(255, 255, 255));
        mid1_8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_7.setBackground(new java.awt.Color(255, 255, 255));
        mid1_7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_6.setBackground(new java.awt.Color(255, 255, 255));
        mid1_6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_5.setBackground(new java.awt.Color(255, 255, 255));
        mid1_5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_4.setBackground(new java.awt.Color(255, 255, 255));
        mid1_4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_3.setBackground(new java.awt.Color(255, 255, 255));
        mid1_3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_2.setBackground(new java.awt.Color(255, 255, 255));
        mid1_2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid1_1.setBackground(new java.awt.Color(255, 255, 255));
        mid1_1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_9.setBackground(new java.awt.Color(255, 255, 255));
        last1_9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_8.setBackground(new java.awt.Color(255, 255, 255));
        last1_8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_7.setBackground(new java.awt.Color(255, 255, 255));
        last1_7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_6.setBackground(new java.awt.Color(255, 255, 255));
        last1_6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_5.setBackground(new java.awt.Color(255, 255, 255));
        last1_5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_4.setBackground(new java.awt.Color(255, 255, 255));
        last1_4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_3.setBackground(new java.awt.Color(255, 255, 255));
        last1_3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_2.setBackground(new java.awt.Color(255, 255, 255));
        last1_2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last1_1.setBackground(new java.awt.Color(255, 255, 255));
        last1_1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_9.setBackground(new java.awt.Color(255, 255, 255));
        top2_9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_9.setBackground(new java.awt.Color(255, 255, 255));
        mid2_9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_9.setBackground(new java.awt.Color(255, 255, 255));
        last2_9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_8.setBackground(new java.awt.Color(255, 255, 255));
        last2_8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_8.setBackground(new java.awt.Color(255, 255, 255));
        mid2_8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_8.setBackground(new java.awt.Color(255, 255, 255));
        top2_8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_7.setBackground(new java.awt.Color(255, 255, 255));
        top2_7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_7.setBackground(new java.awt.Color(255, 255, 255));
        mid2_7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_7.setBackground(new java.awt.Color(255, 255, 255));
        last2_7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_6.setBackground(new java.awt.Color(255, 255, 255));
        last2_6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_6.setBackground(new java.awt.Color(255, 255, 255));
        mid2_6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_6.setBackground(new java.awt.Color(255, 255, 255));
        top2_6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_5.setBackground(new java.awt.Color(255, 255, 255));
        top2_5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_4.setBackground(new java.awt.Color(255, 255, 255));
        top2_4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_3.setBackground(new java.awt.Color(255, 255, 255));
        top2_3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_2.setBackground(new java.awt.Color(255, 255, 255));
        top2_2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        top2_1.setBackground(new java.awt.Color(255, 255, 255));
        top2_1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        top2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_1.setBackground(new java.awt.Color(255, 255, 255));
        mid2_1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_1.setBackground(new java.awt.Color(255, 255, 255));
        last2_1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_2.setBackground(new java.awt.Color(255, 255, 255));
        last2_2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_3.setBackground(new java.awt.Color(255, 255, 255));
        last2_3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_2.setBackground(new java.awt.Color(255, 255, 255));
        mid2_2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_4.setBackground(new java.awt.Color(255, 255, 255));
        last2_4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        last2_5.setBackground(new java.awt.Color(255, 255, 255));
        last2_5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        last2_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_5.setBackground(new java.awt.Color(255, 255, 255));
        mid2_5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_4.setBackground(new java.awt.Color(255, 255, 255));
        mid2_4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mid2_3.setBackground(new java.awt.Color(255, 255, 255));
        mid2_3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        mid2_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLAYER-1 TICKET TABLE");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLAYER-2 TICKET TABLE");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Player_Group.add(player_1);
        player_1.setText("PLAYER-1");
        player_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_1ActionPerformed(evt);
            }
        });

        Player_Group.add(player_2);
        player_2.setText("PLAYER-2");

        early_five.setBackground(new java.awt.Color(0, 204, 0));
        early_five.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        early_five.setForeground(new java.awt.Color(255, 255, 255));
        early_five.setText("EARLY FIVE");
        early_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                early_fiveActionPerformed(evt);
            }
        });

        top_level.setBackground(new java.awt.Color(0, 204, 0));
        top_level.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        top_level.setForeground(new java.awt.Color(255, 255, 255));
        top_level.setText("TOP ROW");
        top_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top_levelActionPerformed(evt);
            }
        });

        middle_row.setBackground(new java.awt.Color(0, 204, 0));
        middle_row.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        middle_row.setForeground(new java.awt.Color(255, 255, 255));
        middle_row.setText("MIDDLE ROW");
        middle_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle_rowActionPerformed(evt);
            }
        });

        last_row.setBackground(new java.awt.Color(0, 204, 0));
        last_row.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        last_row.setForeground(new java.awt.Color(255, 255, 255));
        last_row.setText("LAST ROW");
        last_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_rowActionPerformed(evt);
            }
        });

        four_corner.setBackground(new java.awt.Color(0, 204, 0));
        four_corner.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        four_corner.setForeground(new java.awt.Color(255, 255, 255));
        four_corner.setText("FOUR CORNER");
        four_corner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_cornerActionPerformed(evt);
            }
        });

        full_table.setBackground(new java.awt.Color(0, 204, 0));
        full_table.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        full_table.setForeground(new java.awt.Color(255, 255, 255));
        full_table.setText("FULL TABLE");
        full_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_tableActionPerformed(evt);
            }
        });

        rules.setBackground(new java.awt.Color(51, 0, 51));
        rules.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        rules.setForeground(new java.awt.Color(204, 204, 255));
        rules.setText("RULES");
        rules.setBorder(null);
        rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesActionPerformed(evt);
            }
        });

        j1.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        j1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        j1.setText("PLAYER-1:");
        j1.setPreferredSize(new java.awt.Dimension(84, 22));

        j2.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        j2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        j2.setText("PLAYER-2:");

        score_1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N

        score_2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rules, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(mid2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(top2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(last2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(last2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(last_row, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(middle_row, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(top_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(early_five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(four_corner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(full_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(mid1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(mid1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(top1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(top1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(last1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(last1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(last1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(last1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(last1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(last1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)))
                                        .addGap(0, 0, 0)
                                        .addComponent(last1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(last1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(last1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(player_1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(player_2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(score_2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(score_1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(top1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(top1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(top1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(top1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(top1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(top1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(top1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(top1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(top1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mid1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mid1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mid1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mid1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mid1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mid1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mid1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mid1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mid1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(last1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(last1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(last1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(score_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(score_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(player_1)
                                        .addGap(51, 51, 51))
                                    .addComponent(player_2))
                                .addGap(140, 140, 140))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(early_five, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(top_level, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(middle_row, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(last_row, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(full_table, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(four_corner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(rules, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(top2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(top2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(top2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(top2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(top2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(top2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(top2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(top2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(top2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mid2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mid2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mid2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mid2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mid2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mid2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mid2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mid2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mid2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(last2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(last2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(last2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(last2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(last2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(last2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(last2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(last2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(last2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed

        
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        
        
    }//GEN-LAST:event_Btn1ActionPerformed

    private void player_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_1ActionPerformed

    private void early_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_early_fiveActionPerformed
        
        if(getSelectedRadioButton().equals("PLAYER-1"))
        {
            int cnt =0;
            for(int i=0;i<9;i++)
            {
                if(top_1[i].getText().equals("X"))
                        cnt++;
                if(mid_1[i].getText().equals("X"))
                        cnt++;
                if(last_1[i].getText().equals("X"))
                        cnt++;
                if(cnt >= 5)
                    break;
            }
            if(cnt >= 5)
            {
                P1_count += 50;
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this, congo,"Early Five",JOptionPane.INFORMATION_MESSAGE);
                early_five.setVisible(false);
                score_1.setText(String.valueOf(P1_count));
            }
            else
            {
                JOptionPane.showMessageDialog(this,  "YOU ARE BOOGIE ","Early Five",JOptionPane.WARNING_MESSAGE);
                //TODO
            }
        }
        else if(getSelectedRadioButton().equals("PLAYER-2"))
        {
            int cnt =0;
            for(int i=0;i<9;i++)
            {
                if(top_2[i].getText().equals("X"))
                        cnt++;
                if(mid_2[i].getText().equals("X"))
                        cnt++;
                if(last_2[i].getText().equals("X"))
                        cnt++;
                if(cnt >= 5)
                    break;
            }
            if(cnt >= 5)
            {
                P2_count += 50;
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this,  congo,"Early Five",JOptionPane.INFORMATION_MESSAGE);
                early_five.setVisible(false);
                score_2.setText(String.valueOf(P2_count));
                
                //TODO 
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Early Five", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_early_fiveActionPerformed

    private void top_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top_levelActionPerformed
        boolean isWin=true,p1=false,p2=false;
        if(getSelectedRadioButton().equals("PLAYER-1"))
        {
            p1 = true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(top_1[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
        }
        else if(getSelectedRadioButton().equals("PLAYER-2"))
        {
            p2 = true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(top_2[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
        }
        if(!getSelectedRadioButton().equals(""))
        {
            if(isWin){
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this, congo,"Top Row", JOptionPane.INFORMATION_MESSAGE);
                top_level.setVisible(false);
                if(p1){
                    P1_count +=50;
                    score_1.setText(String.valueOf(P1_count));
                }
                else if(p2){
                    P2_count +=50;
                    score_2.setText(String.valueOf(P2_count));
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"YOU ARE BOOGIE ", "Top Row", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_top_levelActionPerformed

    private void middle_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle_rowActionPerformed
        // TODO add your handling code here:
        boolean isWin=true,p1=false,p2=false;
        if(getSelectedRadioButton().equals("PLAYER-1"))
        {
            p1=true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(mid_1[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
        }
        else if(getSelectedRadioButton().equals("PLAYER-2"))
        {
            p2=true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(mid_2[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
        }
        if(!getSelectedRadioButton().equals(""))
        {
            if(isWin){
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this, congo,"Middle Row", JOptionPane.INFORMATION_MESSAGE);
                middle_row.setVisible(false);
                if(p1){
                    P1_count +=50;
                    score_1.setText(String.valueOf(P1_count));
                }
                else if(p2){
                    P2_count +=50;
                    score_2.setText(String.valueOf(P2_count));
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Middle Row", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_middle_rowActionPerformed

    private void last_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_rowActionPerformed
        
        boolean isWin=true,p1=false,p2=false;
        if(getSelectedRadioButton().equals("PLAYER-1"))
        {    
            p1=true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(last_1[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
        }
        else if(getSelectedRadioButton().equals("PLAYER-2"))
        {
            p2=true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(last_2[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
            
        }
        if(!getSelectedRadioButton().equals(""))
        {
            if(isWin){
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this, congo,"Last Row", JOptionPane.INFORMATION_MESSAGE);
                last_row.setVisible(false);
                if(p1)
                {
                    P1_count +=50;
                    score_1.setText(String.valueOf(P1_count));
                }
                else if(p2){
                    P2_count +=50;
                    score_2.setText(String.valueOf(P2_count));
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Last Row", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_last_rowActionPerformed

    private void four_cornerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_cornerActionPerformed
        
        if(getSelectedRadioButton().equals("PLAYER-1"))
        {
            if(isNumeric(top_1[0].getText()) || isNumeric(top_1[8].getText()) || isNumeric(last_1[0].getText()) || isNumeric(last_1[8].getText()))
            {
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Four Corner", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                P1_count +=50;
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this, congo,"Four Corner", JOptionPane.INFORMATION_MESSAGE);
                four_corner.setVisible(false);
                score_1.setText(String.valueOf(P1_count));
            }
        }
        else if(getSelectedRadioButton().equals("PLAYER-2"))
        {
            if(isNumeric(top_2[0].getText()) || isNumeric(top_2[8].getText()) || isNumeric(last_2[0].getText()) || isNumeric(last_2[8].getText()))
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Four Corner", JOptionPane.WARNING_MESSAGE);
            else
            {
                P2_count +=50;
                String congo = "Congratulations! You got 50 Bonus points";
                JOptionPane.showMessageDialog(this, congo,"Four Corner", JOptionPane.INFORMATION_MESSAGE);
                four_corner.setVisible(false);
                score_2.setText(String.valueOf(P2_count));
            }
        }   
    }//GEN-LAST:event_four_cornerActionPerformed

    @SuppressWarnings("empty-statement")
    private void full_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_tableActionPerformed
        // TODO add your handling code here:
        if(getSelectedRadioButton().equals("PLAYER-1"))
        {
            boolean isWin = true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(top_1[i].getText()) || isNumeric(mid_1[i].getText()) || isNumeric(last_1[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
            if(isWin)
              JOptionPane.showMessageDialog(this, "Congratualations! Player-1 won the game", "WINNER", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Full Table", JOptionPane.WARNING_MESSAGE);
        }
        else if(getSelectedRadioButton().equals("PLAYER-2"))
        {
            boolean isWin = true;
            for(int i=0;i<9;i++)
            {
                if(isNumeric(top_2[i].getText()) || isNumeric(mid_2[i].getText()) || isNumeric(last_2[i].getText()))
                {
                    isWin = false;
                    break;
                }
            }
            if(isWin)
                JOptionPane.showMessageDialog(this, "Congratualations! Player-2 won the game", "WINNER", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "YOU ARE BOOGIE ","Full Table", JOptionPane.WARNING_MESSAGE);
        }
        int dialogOption = JOptionPane.showConfirmDialog(this, "Do you wish to play again?", "TAMBOOLA", JOptionPane.YES_NO_OPTION);
                if(dialogOption == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showConfirmDialog(this, "THANK YOU!", "TAMBOOLA", JOptionPane.OK_OPTION);
                    System.exit(0);
                }
                else
                    restart();
                
    }//GEN-LAST:event_full_tableActionPerformed

    private void rulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesActionPerformed
        // TODO add your handling code here:
        RULES_AND_REGULATIONS r = new RULES_AND_REGULATIONS();
        r.setVisible(true);
    }//GEN-LAST:event_rulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel NUMBER;
    private javax.swing.ButtonGroup Player_Group;
    private javax.swing.JButton early_five;
    private javax.swing.JButton four_corner;
    private javax.swing.JButton full_table;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton last1_1;
    private javax.swing.JButton last1_2;
    private javax.swing.JButton last1_3;
    private javax.swing.JButton last1_4;
    private javax.swing.JButton last1_5;
    private javax.swing.JButton last1_6;
    private javax.swing.JButton last1_7;
    private javax.swing.JButton last1_8;
    private javax.swing.JButton last1_9;
    private javax.swing.JButton last2_1;
    private javax.swing.JButton last2_2;
    private javax.swing.JButton last2_3;
    private javax.swing.JButton last2_4;
    private javax.swing.JButton last2_5;
    private javax.swing.JButton last2_6;
    private javax.swing.JButton last2_7;
    private javax.swing.JButton last2_8;
    private javax.swing.JButton last2_9;
    private javax.swing.JButton last_row;
    private javax.swing.JButton mid1_1;
    private javax.swing.JButton mid1_2;
    private javax.swing.JButton mid1_3;
    private javax.swing.JButton mid1_4;
    private javax.swing.JButton mid1_5;
    private javax.swing.JButton mid1_6;
    private javax.swing.JButton mid1_7;
    private javax.swing.JButton mid1_8;
    private javax.swing.JButton mid1_9;
    private javax.swing.JButton mid2_1;
    private javax.swing.JButton mid2_2;
    private javax.swing.JButton mid2_3;
    private javax.swing.JButton mid2_4;
    private javax.swing.JButton mid2_5;
    private javax.swing.JButton mid2_6;
    private javax.swing.JButton mid2_7;
    private javax.swing.JButton mid2_8;
    private javax.swing.JButton mid2_9;
    private javax.swing.JButton middle_row;
    private javax.swing.JRadioButton player_1;
    private javax.swing.JRadioButton player_2;
    private javax.swing.JButton rules;
    private javax.swing.JLabel score_1;
    private javax.swing.JLabel score_2;
    private javax.swing.JButton top1_1;
    private javax.swing.JButton top1_2;
    private javax.swing.JButton top1_3;
    private javax.swing.JButton top1_4;
    private javax.swing.JButton top1_5;
    private javax.swing.JButton top1_6;
    private javax.swing.JButton top1_7;
    private javax.swing.JButton top1_8;
    private javax.swing.JButton top1_9;
    private javax.swing.JButton top2_1;
    private javax.swing.JButton top2_2;
    private javax.swing.JButton top2_3;
    private javax.swing.JButton top2_4;
    private javax.swing.JButton top2_5;
    private javax.swing.JButton top2_6;
    private javax.swing.JButton top2_7;
    private javax.swing.JButton top2_8;
    private javax.swing.JButton top2_9;
    private javax.swing.JButton top_level;
    // End of variables declaration//GEN-END:variables
}
